### ISSUE TITLE
Version issues of python and other dependencies

### ISSUE THREAD

**Issue by PenglongHuang** [thehamkercat/NSFW_Detection_API#2]
Hello, what is the version of python and other dependencies used by this project. Looking forward for your reply, thank you.

**Comment by TheHamkerCat** [comment]
Latest version of all the dependencies with python <= 3.9 should work, Can you show what error you're getting?

**Comment by wuyaguilao** [comment]
> Latest version of all the dependencies with python <= 3.9 should work, Can you show what error you're getting?

TypeError: Error when deserializing class 'KerasLayer' using config={'name': 'keras_layer', 'trainable': True, 'dtype': 'float32', 'handle': 'https://tfhub.dev/google/imagenet/mobilenet_v2_140_224/feature_vector/4', 'batch_input_shape': [None, 224, 224, 3]}.

**Comment by TheHamkerCat** [comment]
While I don't know why it's not working on your system, I've just added support for docker, this should work for you and everyone else:

https://github.com/TheHamkerCat/NSFW_Detection_API#docker
